name: .NET Build Test and Publish artifacts

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Restore dependencies
      run: dotnet restore -v n /p:EnableWindowsTargeting=true
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal /p:EnableWindowsTargeting=true
  publish-avalonia:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        runtime: [win-x64, win-arm64, linux-x64, linux-arm64, osx-x64, osx-arm64]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Build
      working-directory: TomodachiDrawer.UI.Avalonia
      run: dotnet publish --configuration ${{ matrix.configuration }} -r ${{ matrix.runtime }} --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true ${{ github.ref_type == 'tag' && format('-p:Version={0}', github.ref_name) || '' }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: TomodachiDrawer-Avalonia-${{ matrix.runtime }}-${{ matrix.configuration }}
        path: TomodachiDrawer.UI.Avalonia/bin/${{ matrix.configuration }}/net10.0/${{ matrix.runtime }}/publish/
  release:
    name: Draft release
    runs-on: ubuntu-latest
    needs: publish-avalonia
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v6
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: unzipped-artifacts
        merge-multiple: false
    - name: Zip for Release
      run: |
        mkdir final-packages
        for dir in unzipped-artifacts/*/; do
          dirname=$(basename "$dir")
          cd "$dir"
          echo "Zipping/Tarring ${dirname}"
          
          outname="${dirname//osx/mac}"
          
          if [[ "$dirname" == *"linux"* ]] || [[ "$dirname" == *"osx"* ]]; then
            echo "Linux/Mac .tar.gz"
            chmod +x TomodachiDrawer.UI.Avalonia
            tar -czvf "../../final-packages/${outname}-${{ github.ref_name }}.tar.gz" *
          else
            echo "Windows .zip"
            zip -r "../../final-packages/${outname}-${{ github.ref_name }}.zip" .
          fi
          cd ../..
        done
    - name: Create release draft
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name}} final-packages/* --draft --generate-notes --title "${{ github.ref_name }} - RELEASENAME_REPLACEME"