name: .NET Build And Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Restore dependencies
      run: dotnet restore -v n /p:EnableWindowsTargeting=true
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal /p:EnableWindowsTargeting=true
  publish-avalonia:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Release, Debug]
        runtime: [win-x64, linux-x64,linux-arm64,osx-x64,osx-arm64]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: cd
      run: cd TomodachiDrawer.UI.Avalonia
    - name: Build
      run: dotnet publish --configuration ${{ matrix.configuration }} -r ${{ matrix.runtime }} --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    # todo: artifacts, release flow, etc?
