name: .NET Build And Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Restore dependencies
      run: dotnet restore -v n /p:EnableWindowsTargeting=true
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal /p:EnableWindowsTargeting=true
  publish-avalonia:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        runtime: [win-x64, linux-x64,linux-arm64,osx-x64,osx-arm64]

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Build
      working-directory: TomodachiDrawer.UI.Avalonia
      run: dotnet publish --configuration ${{ matrix.configuration }} -r ${{ matrix.runtime }} --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    # todo: artifacts, release flow, etc?
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: TomodachiDrawer-${{ matrix.runtime }}-${{ matrix.configuration }}
        # Point to where dotnet actually puts the files
        path: TomodachiDrawer.UI.Avalonia/bin/${{ matrix.configuration }}/net10.0/${{ matrix.runtime }}/publish/
  publish-windows:
    runs-on: windows-latest 
    needs: build
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        cache: true
        cache-dependency-path: '**/*.csproj'
    - name: Publish WinForms
      working-directory: TomodachiDrawer.UI.Windows
      run: dotnet publish --configuration ${{ matrix.configuration }} -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: TomodachiDrawer-WinForms-${{ matrix.configuration }}
        path: TomodachiDrawer.UI.Windows/bin/${{ matrix.configuration }}/net10.0-windows/win-x64/publish/